# Generated by Django 3.1.7 on 2021-06-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nbaTeam',
            fields=[
                ('team_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_logo', models.URLField()),
                ('team_division', models.CharField(max_length=50)),
                ('team_city', models.CharField(max_length=50)),
                ('active_roster_cap', models.IntegerField(null=True)),
                ('dead_cap', models.IntegerField(null=True)),
                ('cap_hold', models.IntegerField(null=True)),
                ('total_cap', models.IntegerField(null=True)),
                ('cap_max_space', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nbaPlayer',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('jersey_number', models.IntegerField()),
                ('player_image', models.URLField(null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField(null=True)),
                ('draft_year', models.CharField(max_length=20)),
                ('draft_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('contract_year', models.IntegerField(null=True)),
                ('contract_amount', models.IntegerField(null=True)),
                ('average_salary', models.IntegerField(null=True)),
                ('signed_using', models.CharField(max_length=50)),
                ('base_salary', models.IntegerField(null=True)),
                ('dead_cap', models.IntegerField(null=True)),
                ('cap_figure', models.IntegerField(null=True)),
                ('cap_percentage', models.FloatField(null=True)),
                ('future_guranteed', models.IntegerField(null=True)),
                ('injury', models.CharField(max_length=20)),
                ('season_ending_injury', models.BooleanField(default=False)),
                ('player_team', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='nba.nbateam')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
