# Generated by Django 3.1.7 on 2021-04-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_conference',
        ),
    ]
