# Generated by Django 3.1.7 on 2021-06-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nbaPlayer',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='nbaTeam',
            new_name='Team',
        ),
    ]
