# Generated by Django 3.2 on 2021-05-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_remove_team_team_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercareerstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerseasonstats',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='playerseasonstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='SeasonStats',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='team',
        ),
        migrations.DeleteModel(
            name='PlayerCareerStats',
        ),
        migrations.DeleteModel(
            name='PlayerSeasonStats',
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
        migrations.DeleteModel(
            name='TeamSeasonStats',
        ),
    ]
