# Generated by Django 3.2.1 on 2021-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_auto_20210504_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='dob',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='draft_round',
            new_name='injury',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='jersey',
            new_name='jersey_number',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='average_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='season_ending_injury',
            field=models.BooleanField(default=False),
        ),
    ]
