# Generated by Django 3.2.1 on 2021-05-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_auto_20210511_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='postition',
            new_name='position',
        ),
    ]
