# Generated by Django 3.2.1 on 2021-05-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_rename_postition_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus',
            field=models.IntegerField(null=True),
        ),
    ]
