# Generated by Django 3.2.1 on 2021-05-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_player_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
