# Generated by Django 3.2.1 on 2021-05-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_auto_20210511_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
    ]
