# Generated by Django 3.2.1 on 2021-05-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_rename_team_player_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team_name_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bonus',
        ),
    ]
