# Generated by Django 3.2.1 on 2021-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_auto_20210511_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
