# Generated by Django 3.2.1 on 2021-05-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_alter_player_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name_id',
            new_name='team_name',
        ),
    ]
