# Generated by Django 3.2.1 on 2021-05-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0012_rename_team_name_id_player_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team',
        ),
    ]
